// SPDX-License-Identifier: Apache-2.0
//
// Emits spec/fixtures/golden_devnet_transfer_hook.json from the TypeScript
// reference resolver, so the Ruby resolver in lib/ioniqx_rwa_client/
// extra_account_metas.rb can be asserted byte-identical against it.
//
// The reference is `resolveExtraAccountMetasForExecute` from
// @solana-program/token-2022 — the kit-era successor to the legacy
// @solana/spl-transfer-hook `addExtraAccountMetasForExecute`. Using the real
// helper rather than a hand-written oracle is the whole point: a fixture
// generated by our own understanding of the spec would encode our own bugs.
//
// Usage:
//   cd scripts && npm install
//   IONIQX_HOOK_PROGRAM_ID=... IONIQX_MINT=... IONIQX_SOURCE=... \
//   IONIQX_DESTINATION=... IONIQX_AUTHORITY=... npm run emit
//
// Then run the Ruby parity test against it:
//   IONIQX_GOLDEN_DEVNET=1 bundle exec rspec
//
// Requires a mint whose transfer hook validation account (the
// ExtraAccountMetaList PDA) actually exists on the target cluster. Without one
// the reference returns [] and there is nothing to pin.

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { createSolanaRpc, isSignerRole, isWritableRole } from "@solana/kit";
import { resolveExtraAccountMetasForExecute } from "@solana-program/token-2022";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, "../spec/fixtures/golden_devnet_transfer_hook.json");

function required(name) {
  const value = process.env[name];
  if (!value) {
    console.error(`missing required env var ${name}`);
    process.exit(2);
  }
  return value;
}

const rpcUrl = process.env.SOLANA_RPC_URL ?? "https://api.devnet.solana.com";

const input = {
  hook_program_id: required("IONIQX_HOOK_PROGRAM_ID"),
  mint: required("IONIQX_MINT"),
  source: required("IONIQX_SOURCE"),
  destination: required("IONIQX_DESTINATION"),
  authority: required("IONIQX_AUTHORITY"),
  amount: Number(process.env.IONIQX_AMOUNT ?? 1_000_000)
};

const rpc = createSolanaRpc(rpcUrl);

const metas = await resolveExtraAccountMetasForExecute({
  rpc,
  transferHookProgramAddress: input.hook_program_id,
  mint: input.mint,
  source: input.source,
  destination: input.destination,
  owner: input.authority,
  amount: input.amount
});

if (metas.length === 0) {
  console.error(
    `no ExtraAccountMetaList found for mint ${input.mint} under hook ` +
      `${input.hook_program_id} on ${rpcUrl}.\n` +
      "The reference returns [] when a mint has no validation account, so " +
      "there is nothing to pin. Deploy the hook and initialize the list first."
  );
  process.exit(1);
}

// The Ruby resolver returns plain hashes carrying pubkey/signer/writable, so
// kit's AccountRole bitmask is decomposed back into the two booleans here.
const expected = metas.map((meta) => ({
  pubkey: String(meta.address),
  signer: isSignerRole(meta.role),
  writable: isWritableRole(meta.role)
}));

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, `${JSON.stringify({ ...input, expected }, null, 2)}\n`);

console.log(`wrote ${OUT}`);
console.log(`${expected.length} accounts (last two are the hook program and its validation account)`);
